name: Develop workflow ms-auth

permissions:
  contents: write

on:
  pull_request:
    branches:
      - develop
    paths:
      - "apps/ms-auth/**"

jobs:
  commit-lint:
    name: Verify conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml

  ms_auth-linter-test:
    runs-on: ubuntu-latest
    needs: commit-lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile

      - name: Lint ms-auth
        run: pnpm --filter ms-auth lint

  ms_auth-build-test:
    runs-on: ubuntu-latest
    needs: commit-lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile

      - name: Build ms-auth
        run: pnpm --filter ms-auth build

  ms_auth-jest-test:
    runs-on: ubuntu-latest
    needs: commit-lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm --filter ms-auth test

  ms_auth-jest-cov-test:
    runs-on: ubuntu-latest
    needs: commit-lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile

      - name: Run coverage
        run: pnpm --filter ms-auth test:cov